[build-system]
requires = ["setuptools==75.8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lacam-dte"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["openpyxl==3.1.5", "matplotlib==3.10.0"]

[project.optional-dependencies]
dev = ["pytest==8.3.4"]

[project.scripts]
lacam-dte = "lacam_dte.cli:main"

[tool.setuptools]
packages = ["lacam_dte"]

[tool.pytest.ini_options]
testpaths = ["tests"]
